### PR TITLE
Test_Cases_nightly_apinf_dashboard_05_07_2017

### PR DESCRIPTION
**Pull request by saralavanip**
Updated/edited test case suits: 14.2, 15

### CODE REVIEW

**Comment by bajiat** [comment]
Could we have a version history in the document instead of only the most recent changes? A table that contains a revision number, date and list of changes? How does that sound to you?

**Comment by bajiat** [comment]
Comment on "14.2 Add 'eMQ' Proxy"

"Expected Result: Successful adding 'eMQ' as  proxy "

Please add the criteria for successful: Minimum requirement would be e.g. if the user revisits the Settings page, the broker is included on the Settings page.

Also, please add criteria for successful in test cases 14.3 and 14.4

**Comment by bajiat** [comment]
Comment on "15.3 Connect APIs to organization  "

"Expected Result: Displays successful message  'Connecting API to organization successful'"

Do not rely on the user notification when determining whether an action was successful or not. Rather you could say that if you navigate to the organization profile, you can see the connected API or APIs on the profile.

**Comment by saralavanip** [comment]
Closing this PR and another new PR been created.

**Pull request closed without merging**
