### PR TITLE
APINF <-> FIWARE Business API Ecosystem

### PR DESCRIPTION
**Pull request by brylie**
Create diagram of hypothetical integration between APInf and the FIWARE Business API Ecosystem.

### CODE REVIEW

**Comment by mauriciovieira** [comment]
For quick visualization https://www.draw.io/#Hapinf%2Fdocs%2Ffiware-business-api-ecosystem-integration%2Fdocs%2Fdevelop%2FArchitecture%2FFIWARE-Business_API_Ecosystem-integration.xml

**Comment by mauriciovieira** [comment]
@brylie what does CDR stand for?

**Comment by brylie** [comment]
The closest definition I can find, from my understanding, is [Charging Data Record](https://en.wikipedia.org/wiki/Charging_data_record). The [FIWARE Business API Ecosystem docs](http://docs.fiwaretmfbizecosystem.apiary.io/) describe the [CDRs Transactions - Management API](http://docs.fiwaretmfbizecosystem.apiary.io/#reference/cdrs-transactions-management-api) as:

> API for the management of CDR documents describing transactions. This API allows to register transactions. Additionally, this API allows to launch the settlement process that aggregates the transactions and calculates the distribution of revenues.

**Comment by bajiat** [comment]
My comments are in the issue

**Comment by bajiat** [comment]
@mauriciovieira Could you review the diagram? If everything looks ok, please merge. Note that this is the first revision and subject to change.

**Comment by mauriciovieira** [comment]
LGTM

**Pull request merged**
