### PR TITLE
Add conclusion on research of Zabbix vs Prometheus.

### PR DESCRIPTION
**Pull request by shaliko**
/cc @bajiat @brylie Feel free change description, my English not very good.

### CODE REVIEW

**Comment by brylie** [comment]
If we decide to integrate Prometheus into Apinf, how can we remotely configure the Prometheus service? E.g. when adding a new API to Apinf, we might give an option for the owner to enable API service level monitoring. Does Prometheus have a REST configuration interface? 

Also, what would be some options for retrieving analytics data from Prometheus? For instance, we may want to display metrics/status indicator in the Apinf user interface.

**Comment by brylie** [comment]
There are two main use cases for a service monitoring solution:
- monitoring our **internal services**
- providing an **external service monitoring** integration into our Apinf tool

For the **internal service monitoring** purposes, we can do any sort of manual configuration deemed reasonable. 

For the **external service monitoring** integration, we need a way to update the monitoring configuration from a JavaScript environment, possibly over HTTP, where we may not be able to install any metric instruments on the remote system.

**Comment by brylie** [comment]
@bajiat and @ccsr is my understanding correct?

**Comment by shaliko** [comment]
@brylie No, it dose not have REST configuration interface. But we have bunch way how add new node endpoint for fetch stats https://prometheus.io/docs/operating/configuration/.

"option for the owner to enable API service level monitoring" And what owner should have then? Metrics will be collect on our prometheus server, you mean case when we need give access to our prometheus dashboard to customer? Please describe more what owner may want.

**Comment by brylie** [comment]
By way of example, Hynek Schlawack made the following generalizations at his [PyCon 2016 presentation](https://www.youtube.com/watch?v=b-qLOY5ChnQ):

> [Prometheus is mostly used by people who run their own infrastructure](https://youtu.be/b-qLOY5ChnQ?t=1167)
> 
> [Prometheus is intended to run in the same network as its targets](https://youtu.be/b-qLOY5ChnQ?t=1175)

**Comment by brylie** [comment]
> "option for the owner to enable API service level monitoring" And what owner should have then? Metrics will be collect on our prometheus server, you mean case when we need give access to our prometheus dashboard to customer? Please describe more what owner may want.

Basically, when an end-user, such as an API owner, adds an API to Apinf, they can enable monitoring. We currently do a simple ping check to check that an API is 'alive' when viewing the API details page. We would like to offer more in-depth monitoring details, directly in the Apinf user interface.

**Comment by brylie** [comment]
In effect, we would request service status/analytics data from the monitoring server and render them in the Apinf user interface.

**Comment by brylie** [comment]
Here is a screenshot for more context:

screenshot from 2016-06-02 12-14-57

In the screenshot, we are monitoring the Google.com endpoint, which is not under our control. We simply ping the API endpoint to check for 'aliveness'. We would like to give some additional 'aliveness' or 'quality' metrics, so that end-users can see the quality of a given API.

**Comment by brylie** [comment]
For configuration purposes, we could consider options to move yaml configuration files to the monitoring service. E.g. Node.js can write to the file system and we can sync the config file via rsync.

**Comment by bajiat** [comment]
@brylie @shaliko Brylie's understanding of the use cases is correct. We need to monitor both our services/modules and to monitor the APIs managed by Apinf. See the user story for the latter "As an Apinf user I want to see the percentage of failures/uptime (timeout, bad gateway, internal server error)." Maybe there are even more metrics for the API?
Potentially we could even notify owners of their API is down.

**Comment by ccsr** [comment]
@brylie @shaliko @bajiat Also it should be able to send an mail or sms if the API end point is not working. We need to carefully chose this because we have spent an enormous amount of effort on Zabbix and still we were not able to get it set right. @jykae spent 3 months on it for another customer project and was very difficult. Also we need to ensure that one person in the team should be able to handle setting up and this person also is accountable for it. Might be worth to install it on the servers and try out and see the results.

**Comment by shaliko** [comment]
@brylie @bajiat Thanks for bring more details about how that metric tool will be used and for update description to original story https://github.com/apinf/api-umbrella-dashboard/issues/966

> - providing an external service monitoring integration into our Apinf tool

That is not clear for me. We will collect data from external service and will give access for query to our DB? Will be good have details what mean "internal services" and "external service monitoring".

Based on updated goal of story:

> As an Apinf administrator I want to be notified if any of the Apinf platform services are down

We can store to Prometheus metrics about request timeout/fails and have alert rules for whole API or per API resource. I.e. have different Alert rules for "GET /users" or "POST /users" resources.

> As an API owner I want to be notified if my API is down so that I can take corrective action.

I see here at least 2 options:

1) We can prepare "Alert manager" configuration file and reload Prometheus each times when API owner enable monitoring.

2) Prometheus tool should have only one rule for "Alert manager", just call some endpoint of meteor app with failed host and we will find owner of API and notify it over email or another channel?

> As an Apinf user I want to see the percentage of failures/uptime (timeout, bad gateway, internal server error) for a given API so that I can determine the reliability of a given API backend

We will need integrate Node.JS client library to meteor APP for send data to Prometheus and than use HTTP API for get metrics (percentage of failures/uptime, etc.) Or preferable way use scrapping, meteor APP will just prepare data and Prometheus will periodically pull it. 

Now when I get more details, I am not really sure that we need monitoring tool for manage goals. That story can be splited on 2 parts:

1) Collect/store/query for visualize metrics. Just need DB (MongoDB or preferable TimeSeries like InfluxDB) for store metrics and then fetch it for visualize. As I understood we will not use Prometheus UI component, instead just do query to Prometheus DB and visualize data in Meteor app UI.
2) "Alert system" - just enable/disable alert on "API is down" action. Because APInf is proxy we always know that API is down, then just send email or use SMS gateway for notify admin via phone.

**Comment by shaliko** [comment]
@brylie 

> Prometheus is mostly used by people who run their own infrastructure

What dose it mean? I think that it is also true for most of the monitoring tools. We will not able collect data from not own infrastructure (not have access to data).

> Prometheus is intended to run in the same network as its targets

I don't see any restrictions. If we have access over HTTP we can so scrapping, otherwise need use Prometheus PUSH gateway for send data from app/server to Prometheus.

**Comment by brylie** [comment]
# External services

We want to configure monitoring rules for infrastructure and services that we do not own or manage. E.g. the Google Maps API, which is owned and managed by Google. This is what is meant by _external_ service monitoring -- services/infrastructure that are owned and managed by other organizations where we might be unable to make changes. 

Since we might not be able to change software or daemons on the _external_ services, we need to consider simple ways of monitoring, such as _ping_ and/or _HTTP response codes_.

Related user stories:

> As an API owner I want to be notified if my API is down so that I can take corrective action.
> 
> As an Apinf user I want to see the percentage of failures/uptime (timeout, bad gateway, internal server error) for a given API so that I can determine the reliability of a given API backend

Here is an example:
1. a person registers with apinf.io
2. that person adds an _external_ API backend, such as _Google Maps API_
3. that person wants to monitor the _Google Maps API_ backend
4. our software, Apinf, communicates with the monitoring service and automatically configures a monitoring rule for Google Maps API
5. if some failure threshold is met, the person receives some sort of alert
6. Apinf, occasionally requests monitoring metrics from our monitoring service for the Google Maps API, 
7. Apinf displays those metrics to end users in various forms depending on user role

screenshot from 2016-06-02 12-14-57

# Internal services

We have more control of services/servers used for Apinf deployments, such as apinf.io. On those servers, we can consider making changes that would expose performance metrics to a monitoring service. Related user story here:

> As an Apinf administrator I want to be notified if any of the Apinf platform services are down

The idea of an _internal_ service might also include companies and clients who have given us administrative permissions to manage their servers.

**Comment by brylie** [comment]
# Integration

In the big picture, we are trying to figure out how to integrate an external monitoring service into Apinf. Based on our previous integration work, we want to consider at least the following:
- loose coupling
- programming interface

Our monitoring solution would ideally give us a simple programming interface that we can use for configuration and retrieval of analytics.

## REST-based API

So far, we have integrated with external services, including Github and API Umbrella, primarily via REST APIs. When adding an API backend and/or enabling monitoring, Apinf could call any relevant HTTP endpoints to trigger remote procedures in the monitoring service.

## Text-based configuration

If our monitoring tool uses text-based configuration files, we need to figure out how to create, read, update, and delete those text files from within Apinf codebase. One possible example would be:
1. Apinf creates a text-based configuration file in its local filesystem
2. Apinf somehow pushes that text-based file to the remote monitoring service. E.g. `rsync` or `sftp`
3. the remote monitoring system [re-loads its configuration state](http://www.robustperception.io/reloading-prometheus-configuration/). E.g. via an HTTP POST request

**Comment by brylie** [comment]
> Now when I get more details, I am not really sure that we need monitoring tool for manage goals. That story can be splited on 2 parts:
> 1. Collect/store/query for visualize metrics. Just need DB (MongoDB or preferable TimeSeries like InfluxDB) for store metrics and then fetch it for visualize. As I understood we will not use Prometheus UI component, instead just do query to Prometheus DB and visualize data in Meteor app UI.
> 2. "Alert system" - just enable/disable alert on "API is down" action. Because APInf is proxy we always know that API is down, then just send email or use SMS gateway for notify admin via phone.

I like that line of reasoning. We may be able to simply design a function that checks for HTTP health-signs (e.g. latency, response code) on an interval, and stores the metrics directly in our MongoDB. Then, we can display the metrics in the Apinf UI quite easily, as well as create some alerting functionality (e.g. via email/SMS).

**Comment by brylie** [comment]
@bajiat please review.

**Comment by bajiat** [comment]
@shaliko @brylie @c
So I quess the conclusion is to split the follow-up tasks:
- Install Prometheus for internal service monitoring. 
- For API monitoring, we can write a simple component / function that handles this. 
- For alerting we can use an alert service. 

Right?

I propose that  I first create a follow-up task for installing Prometheus and configuring it for monitoring Apinf, Api Umbrella (and other internal services.)

Would you @shaliko be interested in the installation and configuration task?

**Comment by shaliko** [comment]
@bajiat @brylie Yes, as I understood too, you described tasks right. 

1) Prometheus for internal service monitoring
2) For API monitoring, we can write a simple component / function that handles this.

@bajiat I am interesting to Prometheus installation and configuration task.

**Pull request merged**
