### PR TITLE
Naziaworks

### PR DESCRIPTION
**Pull request by Nazarah**
1. Added "Quality" in sorting
2. table View HiFi wireframes

### CODE REVIEW

**Comment by jykae** [comment]
@elnzv There are also wireframes for card UI.

**Comment by brylie** [comment]
Please avoid using spaces in file/directory names. It causes unexpected behavior when rendering the documentation and managing Git commits. 

Spaces can be replaced with underscores ( _ ), dots ( . ), dashes ( - ), or camelCase notation.

**Comment by jykae** [comment]
Good note @brylie I was only gazing at pictures. Could you rename files @Nazarah ?

**Comment by Nazarah** [comment]
@jykae: I made a commit and tried to merged it to the existing pull request after renaming the file.
But the my github client showed validation failed.
Can you please approve this PR and see how the file names are now?

**Comment by brylie** [comment]
It looks like there are still spaces in some of the file paths:
- Card View - Sorting
- Wireframes/Landing Page/
- Wireframes/Table row and table View/

**Comment by brylie** [comment]
@jykae there are still spaces in the folder name:
- wireframes/[Card View-Sorting/](https://github.com/apinf/docs/tree/master/docs/Wireframes/Card%20View-Sorting)

**Pull request merged**
